### ISSUE TITLE
Header / NavBar Component Creation

### ISSUE THREAD

**Issue by Subhampreet** [storyofams/react-ui#88]
**Is your feature request related to a problem? Please describe.**
Most Website mandatorily have a Navbar element in there website, so having a Header component is must for the package.

**Describe the solution you'd like**
I would like to develop customized Header/Navbar components, with Dark/Light Mode Feature, along with onScroll variations effects

**Comment by mitchelvanbever** [comment]
Hi @Subhampreet! 

Thanks for taking interest in the library we hope it's been treating you right so far 🙏

I have to preface what I'm about to say with the following: _we don't actively maintain this repo since we no longer rely on the ui-kit internally. We can not guarantee a stable user journey for up to date projects or make the promise that any bugs will get ironed out_

Regarding the component itself: We know from experience that the header is one of the more complex components to create meaningful abstractions for (especially with all the features you want to ship it with). Internally we just created the abstraction for those components on a project level (with the help of our fundamentals like Box) instead of opting to add it to the ui kit itself.

Having that said if you want to have a go at it, feel free to create a PR. I'm happy to review the implementation (and get it released if we can settle on a nice abstraction) 🙃 Forking and maintaining your own lib is probably easier / less limiting (so feel free to take that route if you want).

**Comment by Subhampreet** [comment]
Hi @mitchelvanbever 🙋‍♂️! 

Thanks for your response, if the repository is not that well-maintained then I would prefer not to contribute more into the Library. I will proceed with closing of the Issue then.

Thanks Again, and Happy Coding 👨‍💻!
